### ISSUE TITLE
Role fails when FPM not used

### ISSUE THREAD

**Issue by lvampa** [ergontech-ansible-roles/newrelic#3]
```
# Going to do it this way so dependencies on specific handlers is kept at a miniumum
- name: Restart PHP-FPM
  become: yes
  service:
    name: "php{{ php_version }}-fpm"
    state: restarted
```
